name: artemis2d
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - python_abi=3.13
  - numpy=2.4
  - pandas=3.0
  - scipy=1.17
  - matplotlib=3.10
  - matplotlib-base=3.10
  - scikit-image=0.26
  - pillow=12.2
  - imageio=2.37
  - tifffile=2026.6
  - imagecodecs=2026.6
  - networkx=3.6
  - sympy=1.14
  - mpmath=1.4
  - pytorch=2.6.0
  - torchvision=0.21.0
  - cudnn=9.10
  - cuda-version=12.9
  - pyside6=6.11
  - qt6-main=6.11
  - tensorboard=2.20
  - ipykernel=7.3
  - ipython=9.14
  - jupyter_client=8.9
  - jupyter_core=5.9
  - tqdm=4.68
  - psutil=7.2
  - pip
  - pip:
      - cellpose==4.2.1.1
      - fastremap==1.20.0
      - fill-voids==2.1.2
      - matplotlib-scalebar==0.9.0
      - natsort==8.4.0
      - opencv-python-headless==4.13.0.92
      - roifile==2026.2.10
      - segment-anything==1.0
      - setuptools==81.0.0